### ISSUE TITLE
can you show the "bundle.js" origin code?

### ISSUE THREAD

**Issue by WillZWL** [kisslove/web-monitoring#1]
can you show the "bundle.js" origin code?

**Comment by WillZWL** [comment]
Thanks

**Comment by kisslove** [comment]
so sorry,this project only supports online application.if you need more help,explain your purpose.

**Comment by WillZWL** [comment]
Thanks your response, Just want to know how to post all params to server

**Comment by ronniegong** [comment]
请问，上报的js可否开源，想学习一下，谢谢

**Comment by kisslove** [comment]
@ronniegong Thanks for your support. This project only supports online application.
Follow-up, I will publish an online operating guide that details how to collect indicators. Please keep an eye on it.
