### ISSUE TITLE
前台没有设计权限?

### ISSUE THREAD

**Issue by febobo** [kisslove/web-monitoring#11]

**Comment by kisslove** [comment]
目前还没有设计权限，只是用user来区分

**Comment by febobo** [comment]
看了下web， 没有login相关的路由呢？ user 如何使用呢 ?

**Comment by febobo** [comment]
@kisslove 感觉功能还不是很完善，有计划全开源么

**Comment by kisslove** [comment]
请仔细查看登录相关功能。如果有好的建议我们将加入开发计划中，目前只有探针部分未开开源，请持续关注 @febobo

**Comment by febobo** [comment]
好的， 感谢 @kisslove

**Comment by febobo** [comment]
@kisslove 报警功能有计划啥时候上么

**Comment by kisslove** [comment]
报警功能还在需求分析阶段 @febobo

**Comment by kisslove** [comment]
@febobo 报警功能已发布上线

**Comment by febobo** [comment]
> @febobo 报警功能已发布上线

强，发现有很多慢查询...数据一大查的太慢了

**Comment by kisslove** [comment]
这些到线上才会发现真正的问题，分析一下慢慢调优吧
