### ISSUE TITLE
后端支持多节点部署吗 ？

### ISSUE THREAD

**Issue by xuyangxy** [kisslove/web-monitoring#13]
如题

**Comment by xuyangxy** [comment]
大佬，还有个问题，接入后其他都正常，只有资源加载详情没数据，这个是怎么回事呢 ？

**Comment by kisslove** [comment]
1.现在还不支持多节点部署。
2.显示资源加载详情需要勾选配置，如下图：
![image](https://user-images.githubusercontent.com/7383584/69505692-1b75b080-0f66-11ea-97dd-88d0c779b939.png)
@xuyangxy

**Comment by xuyangxy** [comment]
好的  明白了    多谢啦
