### ISSUE TITLE
Msg聚类乱码问题

### ISSUE THREAD

**Issue by xuyangxy** [kisslove/web-monitoring#14]
大佬，问个问题：

API请求--> Msg聚类 -->   显示乱码是啥问题呢，看了下，上报的时候就是乱码该怎么修改呢

**Comment by kisslove** [comment]
你这个是请求返回的是二进制流，因此建议要获取返回的内容，最好使用Blob解析一下，将二进制流转换成字符串就可以了。

**Comment by xuyangxy** [comment]
@kisslove   返回内容也就是个json对象 ， 就调的平时常用的Rest接口服务 ，bunder.js 也没开源，不知道怎么在上报之前处理下

**Comment by kisslove** [comment]
@xuyangxy 这个应该是你下载后的buldle.js的编码问题，里面有中文提示，最好使用utf-8保存

**Comment by xuyangxy** [comment]
好的  我试试看哈
