### ISSUE TITLE
关于type为api类型数据，api接口在ie浏览器下拿不到，怎么解决一下？

### ISSUE THREAD

**Issue by rzechen** [kisslove/web-monitoring#19]
经过查询xmlhttprequest貌似不支持ie

**Comment by kisslove** [comment]
![image](https://user-images.githubusercontent.com/7383584/87490116-6704d800-c677-11ea-83d3-9c3aa658843c.png)
你提的是ie哪个版本？

**Comment by rzechen** [comment]
ie11 ,我看控制台是拿不到responseURL的

**Comment by rzechen** [comment]
![image](https://user-images.githubusercontent.com/24729413/87490566-96681480-c678-11ea-96e7-3676d5e92226.png)

**Comment by rzechen** [comment]
怎么说，大佬？

**Comment by kisslove** [comment]
好的，mark一下，后面看看
