### ISSUE TITLE
一些新功能

### ISSUE THREAD

**Issue by lizhuangs** [kisslove/web-monitoring#2]
网站流量监控、不同地理位置的访问人数、访问量最高的链接排行、访问链接的文件大小排行~
话说我看到的好多都是埋点实现的。。

**Comment by kisslove** [comment]
@lizhuangs 是的，不同的场景，埋点和无埋点上报用户数据各有优势，有些情况两者配合起来使用可能更适合真实需求。所以，我们会提供配置来开启和关闭这种自动上报，并提供api让用户自己来上报数据
