### ISSUE TITLE
linux 下获取操作系统类型

### ISSUE THREAD

**Issue by hanlhan** [kisslove/web-monitoring#22]
你好，网站添加监控代码后，可以正常获取windows和MAC 等操作系统的访问记录，但是linux下的 bundle.js 执行 出错，具体如下：

![](https://user-images.githubusercontent.com/32872034/113397986-6d65ec00-938d-11eb-83ef-f80532ad6b0c.png)

![](https://user-images.githubusercontent.com/32872034/113398738-95a21a80-938e-11eb-9dd1-a5e5b8f1769c.png)

谢谢

**Comment by kisslove** [comment]
@hanlhan 已修复，谢谢反馈。
