### ISSUE TITLE
mongoDB可以提供一下吗？

### ISSUE THREAD

**Issue by cengit** [kisslove/web-monitoring#3]
fork下来自己用一下，发现没有数据库信息啊：mongodb://localhost:27017/monitor2
可以导出数据库信息，提供一下吗？谢谢

**Comment by kisslove** [comment]
@cengit  数据库数据涉及用户数据，但是你可以看一下数据库结构
![image](https://user-images.githubusercontent.com/7383584/56108787-2f911280-5f80-11e9-80fc-249fbfc51d86.png)
