### ISSUE TITLE
node 服务端部署使用了多少资源？

### ISSUE THREAD

**Issue by chping2125** [kisslove/web-monitoring#4]
目前你们支持最大 pv 多少？最大 pv 的项目，聚合查询展示这些数据对于 node 服务端资源有什么要求？

**Comment by kisslove** [comment]
可以使用JMeter来模拟测试，模拟每秒200个用户请求单个聚合查询接口（页面uv/pv概览），目前服务器配置低，win10， 2g内存，node v8.12，测试结果：
![image](https://user-images.githubusercontent.com/7383584/56884799-72cda400-6a9d-11e9-8c02-aadada6f739e.png)
对于pv的换算你可以使用这个链接的算法：
http://www.cnblogs.com/zhengah/p/5160772.html
需要了解更多信息，请关注公众号。
