### ISSUE TITLE
[功能建议]希望能有这样的功能

### ISSUE THREAD

**Issue by yufeng0528** [kisslove/web-monitoring#7]
www.fundebug.com
可视化重现出错场景
:)

**Comment by kisslove** [comment]
你的建议已收到，我们会考虑此功能的开发。如果你有关于这方面的想法和思路，可以随时沟通。

**Comment by kisslove** [comment]
@yufeng0528  已增加场景还原基础功能，可以尝试使用，并提供反馈意见
1.入口
![image](https://user-images.githubusercontent.com/7383584/59913161-3b022d80-944a-11e9-84e4-7b19a1f4f592.png)
2.堆栈信息
![image](https://user-images.githubusercontent.com/7383584/59913242-62f19100-944a-11e9-9fc5-3730d95abc6e.png)
3.错误出现时用户行为
![image](https://user-images.githubusercontent.com/7383584/59913279-73a20700-944a-11e9-9344-fedf43143ea4.png)
